# Generated by Django 4.2.30 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menuitem_emoji_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='emoji',
            field=models.CharField(default='🍽', max_length=10),
        ),
    ]
